title: Hatter's Page
theme: minima

author:
  name: Hatter Jiang
  email: hatter-page@hatterjiang.com

minima:
  social_links:
    - title: jht5945@github
      icon: github
      url: "https://github.com/jht5945"
    - title: Hatter GnuPG
      icon: key
      url: "https://pgp.hatter.me"
