title: Hatter's Page
author:
  name: Hatter Jiang
  email: hatter-page@hatterjiang.com

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  skin: classic
  nav_pages:
    - about.md
  show_excerpts: false
  social_links:
    - title: jht5945@github
      icon: github
      url: "https://github.com/jht5945"
    - title: Hatter GnuPG
      icon: key
      url: "https://pgp.hatter.me"
